{
  "name": "@jymfony/exceptions",
  "version": "0.1.0-alpha.31",
  "description": "Jymfony exception (core package)",
  "main": "index.js",
  "typings": "types/index.d.ts",
  "scripts": {
    "test": "node ./tests.js"
  },
  "keywords": [
    "jymfony",
    "exceptions",
    "errors"
  ],
  "author": "Alessandro Chitolina <alekitto@gmail.com>",
  "license": "MIT",
  "engines": {
    "node": ">=12.0.0"
  },
  "devDependencies": {
    "@jymfony/debug": "*",
    "@jymfony/testing": "*",
    "chai": "^4.2",
    "mocha": "^10.2"
  },
  "config": {
    "jymfony-autoload": {
      "includes": [
        "index.js"
      ]
    },
    "jymfony-autoload-dev": {
      "namespaces": {
        "Jymfony.Exceptions.Tests": "test/"
      }
    }
  }
}
